#!/bin/bash

cargo fmt --all -- --config format_code_in_doc_comments=true

buildargs=(
    "-p nostr"
    "-p nostr --no-default-features"
    "-p nostr --no-default-features --features all-nips"
    "-p nostr --no-default-features --features vanity"
    "-p nostr --features blocking"
    "-p nostr-sdk"
    "-p nostr-sdk --no-default-features"
    "-p nostr-sdk --features blocking"
    "-p nostr-ffi"
    "-p nostr-sdk-ffi"
)

for arg in "${buildargs[@]}"; do
    echo  "Running with '$arg' arg"
    cargo test $arg
    cargo clippy $arg
    echo
done

buildargs=(
    "-p nostr-js --target wasm32-unknown-unknown"
    "-p nostr-sdk-js --target wasm32-unknown-unknown"
)

for arg in "${buildargs[@]}"; do
    echo  "Running with '$arg' arg"
    cargo clippy $arg
    echo
done
