#!/bin/bash

cargo fmt --all -- --config format_code_in_doc_comments=true

buildargs=(
    "-p nostr"
    "-p nostr --no-default-features --features std"
    "-p nostr --no-default-features --features 'std all-nips'"
    "-p nostr --no-default-features --features 'std vanity'"
    "-p nostr --features 'std blocking'"
    "-p nostr-sdk"
    "-p nostr-sdk --no-default-features"
    "-p nostr-sdk --features blocking"
    "-p nostr-ffi"
    "-p nostr-sdk-ffi"
)

for arg in "${buildargs[@]}"; do
    echo  "Running with '$arg' arg"
    cargo test $arg
    cargo clippy $arg
    echo
done
