test: rust python js kotlin flutter swift

rust:
	cd rust && cargo build

python:
	cd python && just test

js:
	cd js && just test

kotlin:
	cd kotlin && just test

flutter:
	cd flutter && just test

swift:
	cd swift && just test
