[package]
name = "nostr-signer"
version = "0.29.0"
edition = "2021"
description = "Signer for Nostr apps"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "signer"]

[features]
default = ["nip04", "nip07", "nip44", "nip46"]
nip04 = ["nostr/nip04"]
nip07 = ["nostr/nip07"]
nip44 = ["nostr/nip44"]
nip46 = ["nostr/nip46", "dep:nostr-relay-pool", "dep:tracing"]

[dependencies]
async-utility.workspace = true
nostr = { workspace = true, features = ["std"] }
nostr-relay-pool = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true, features = ["std", "attributes"], optional = true }
