// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "nostr-sdk-rn.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNostrSdkRnSpec.h"

@interface NostrSdkRn : NSObject <NativeNostrSdkRnSpec>
#else
#import <React/RCTBridgeModule.h>

@interface NostrSdkRn : NSObject <RCTBridgeModule>
#endif

@end