// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'event/tag.dart';
import 'key/public_key.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<_Event>>
abstract class Event implements RustOpaqueInterface {
  String asJson();

  String asPrettyJson();

  /// Get event author (`pubkey` field)
  PublicKey author();

  String content();

  BigInt createdAt();

  static Event fromJson({required String json}) =>
      NostrSdk.instance.api.crateApiProtocolEventEventFromJson(json: json);

  String id();

  /// Returns `true` if the event has an expiration tag that is expired.
  /// If an event has no expiration tag, then it will return `false`.
  ///
  /// <https://github.com/nostr-protocol/nips/blob/master/40.md>
  bool isExpired();

  /// Check if it's a protected event
  ///
  /// <https://github.com/nostr-protocol/nips/blob/master/70.md>
  bool isProtected();

  int kind();

  String signature();

  List<Tag> tags();

  /// Verify both `EventId` and `Signature`
  void verify();

  /// Verify if the `EventId` it's composed correctly
  bool verifyId();

  /// Verify only event `Signature`
  bool verifySignature();
}
