/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsKeys = Keys
export class Keys {
  static fromSecretKey(secretKey: string): JsKeys
  static fromPublicKey(publicKey: string): JsKeys
  static generate(): JsKeys
  static fromMnemonic(mnemonic: string, passphrase?: string | undefined | null): JsKeys
  publicKey(): string
  publicKeyBech32(): string
  secretKey(): string
  secretKeyBech32(): string
}
