/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Keys {
  constructor(sk: string)
  static fromPublicKey(pk: string): Keys
  static fromBech32(sk: string): Keys
  static fromBech32PublicKey(pk: string): Keys
  static generate(): Keys
  publicKey(): string
  secretKey(): string
}
