/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsEventBuilder = EventBuilder
export class EventBuilder {
  constructor(kind: bigint, content: string, tags: Array<Array<string>>)
  toEvent(keys: JsKeys): JsEvent
  toPowEvent(keys: JsKeys, difficulty: number): JsEvent
  static setMetadata(metadata: JsMetadata): this
  static addRecommendedRelay(url: string): this
  static newTextNote(content: string, tags: Array<Array<string>>): this
  static setContactList(list: Array<JsContact>): EventBuilder
  static newEncryptedDirectMsg(senderKeys: JsKeys, receiverPubkey: string, content: string): this
  static repost(eventId: string, publicKey: string): this
  static delete(ids: Array<string>, reason?: string | undefined | null): this
  static newReaction(eventId: string, publicKey: string, content: string): this
}
export type JsEvent = Event
export class Event {
  get id(): string
  get pubkey(): string
  get createdAt(): bigint
  get kind(): bigint
  get tags(): Array<Array<string>>
  get content(): string
  get signature(): string
  verify(): boolean
  static fromJson(json: string): JsEvent
  asJson(): string
}
export type JsKeys = Keys
export class Keys {
  static fromSecretKey(secretKey: string): JsKeys
  static fromPublicKey(publicKey: string): JsKeys
  static generate(): JsKeys
  static fromMnemonic(mnemonic: string, passphrase?: string | undefined | null): JsKeys
  publicKey(): string
  publicKeyBech32(): string
  secretKey(): string
  secretKeyBech32(): string
}
export type JsContact = Contact
export class Contact {
  constructor(publicKey: string, relayUrl?: string | undefined | null, alias?: string | undefined | null)
}
export type JsMetadata = Metadata
export class Metadata {
  constructor()
  static fromJson(json: string): JsMetadata
  asJson(): string
  name(name: string): Metadata
  displayName(displayName: string): Metadata
  about(about: string): Metadata
  website(url: string): this
  picture(url: string): this
  banner(url: string): this
  nip05(nip05: string): Metadata
  lud06(lud06: string): Metadata
  lud16(lud16: string): Metadata
}
export type JsClient = Client
export class Client {
  constructor(keys: JsKeys)
  addRelay(url: string, proxy?: string | undefined | null): Promise<void>
}
