set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

init:
	@wasm-pack --version || cargo install wasm-pack

clean:
    rm -rf ./pkg
    rm -f rust-nostr-*.tgz

publish:
	npm publish --access public

pack: init clean
	bash ./scripts/build.sh
	npm pack
