set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

init:
	@wasm-pack --version || cargo install wasm-pack

clean:
    rm -rf ./pkg
    rm -f rust-nostr-*.tgz
    cd benches && rm -rf node_modules package-lock.json

publish:
	npm publish --access public

pack: init clean
	bash ./scripts/build.sh
	npm pack

bench:
    cd benches && npm install && deno bench
