// Generated by uniffi-bindgen-react-native
#include "nostr-sdk-rn.h"
#include "generated/nostr_sdk.hpp"

namespace nostrsdkrn {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeNostrSdk::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}