[package]
name = "nostr-mls"
version = "0.39.0"
edition = "2021"
description = "A library to help use OpenMLS with Nostr."
authors = ["Jeff Gardner"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "mls", "openmls"]

[dependencies]
openmls = { version = "0.6", git = "https://github.com/openmls/openmls", rev = "e2fc5e1" }
openmls_basic_credential = { version = "0.3", git = "https://github.com/openmls/openmls", rev = "e2fc5e1" }
openmls_rust_crypto = { version = "0.3", git = "https://github.com/openmls/openmls", rev = "e2fc5e1" }
openmls_traits = { version = "0.3", git = "https://github.com/openmls/openmls", rev = "e2fc5e1" }
openmls-sled-storage = { version = "0.1.0", git = "https://github.com/erskingardner/openmls-sled-storage", branch = "master" }
serde = { version = "1", features = ["derive"] }
tls_codec = "0.4"
hex = "0.4"
rand = "0.8"
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
tempfile = "3.13"
