// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `to_secret_bytes`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<_SecretKey>>
abstract class SecretKey implements RustOpaqueInterface {
  static SecretKey fromSlice({required List<int> secretKey}) =>
      NostrSdk.instance.api
          .crateApiProtocolKeySecretKeySecretKeyFromSlice(secretKey: secretKey);

  /// Generate random secret key
  ///
  /// This constructor uses a random number generator that retrieves randomness from the operating system.
  static SecretKey generate() =>
      NostrSdk.instance.api.crateApiProtocolKeySecretKeySecretKeyGenerate();

  /// Parse from `hex` or `bech32`
  static SecretKey parse({required String secretKey}) => NostrSdk.instance.api
      .crateApiProtocolKeySecretKeySecretKeyParse(secretKey: secretKey);

  String toBech32();

  String toSecretHex();
}
