default:
	@just --list
# install book depends
init:
	@mdbook --version || \
	cargo binstall -y --force mdbook --version 0.4.40 || \
	cargo install --force mdbook --version 0.4.40
	@mdbook-linkcheck --version || \
	cargo binstall -y --force mdbook-linkcheck --version 0.7.7 || \
	cargo install --force mdbook-linkcheck --version 0.7.7
	@mdbook-admonish --version || \
	cargo binstall -y --force mdbook-admonish --version 1.15.0 || \
	cargo install --force mdbook-admonish --version 1.15.0
	@mdbook-snippets --version || \
	cargo install --force --path ./snippets-processor

build: init
	mdbook build

serve: init
	mdbook serve

test:
	cd snippets && just test
