default:
	@just --list
# install book depends
init:
	@mdbook --version || cargo install mdbook --version 0.4.40
	@mdbook-linkcheck --version || cargo install mdbook-linkcheck --version 0.7.7
	@mdbook-admonish --version || cargo install mdbook-admonish --version 1.15.0
	@mdbook-snippets --version || cargo install --path ./snippets-processor

build: init
	mdbook build

serve: init
	mdbook serve

test:
	cd snippets && just test
