[private]
init:
	@mdbook --version || cargo install mdbook --version 0.4.36
	@mdbook-admonish --version || cargo install mdbook-admonish --version 1.15.0

build: init
	mdbook build

serve: init
	mdbook serve

test:
	cd snippets && just test
